spring:
  profiles:
    active: local,dev,test,v-product,product
  cloud:
    config:
      server:
        default-label: master
        git:
          uri: https://github.com/winfred958/springframework-cloud.git
          repos:
            local:
              pattern: "*/local*"
              uri: https://github.com/winfred958/springframework-cloud.git
              searchPaths: config-repository/local
            dev:
              pattern: "*/dev*"
              uri: https://github.com/winfred958/springframework-cloud.git
              searchPaths: config-repository/dev
            test:
              pattern: "*/test*"
              uri: https://github.com/winfred958/springframework-cloud.git
              searchPaths: config-repository/test
            v-product:
              pattern: "*/v-product*"
              uri: https://github.com/winfred958/springframework-cloud.git
              searchPaths: config-repository/v-product