spring:
  profiles:
    active: dev,test,v-product,product
  cloud:
    config:
      server:
        git:
          uri: https://github.com/winfred958/springframework-cloud/config-repository/{profile}/{application}
        default-label: master

