eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true
    peer-node-read-timeout-ms: 200
    peer-eureka-nodes-update-interval-ms: 300000
    renewal-percent-threshold: 0.85
    eviction-interval-timer-in-ms: 15000
